// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKrkaEfiCxXnSm7aDLwqZ5D4XGf5LjzIY',
    appId: '1:865677946025:android:e2ba557f3f8bb54b054db8',
    messagingSenderId: '865677946025',
    projectId: 'edu-kita',
    storageBucket: 'edu-kita.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVJyMGdzO4PVw6RZrkYGgw4ED9ADv1TqI',
    appId: '1:865677946025:ios:bff87aa3fd54ced5054db8',
    messagingSenderId: '865677946025',
    projectId: 'edu-kita',
    storageBucket: 'edu-kita.appspot.com',
    androidClientId: '865677946025-pcnqhrhs0i1sg460t41u6dr40o975sqt.apps.googleusercontent.com',
    iosClientId: '865677946025-0s1qkh03imsimclcb739emaeo366epvg.apps.googleusercontent.com',
    iosBundleId: 'com.zrifapps.edukita',
  );

}